import os, io, requests
from PIL import Image
from langchain_groq import ChatGroq
from dotenv import load_dotenv

load_dotenv()

os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_API_KEY")
os.environ["GOOGLE_CX"] = os.getenv("GOOGLE_CX")

def test_single_image_generation():
    """Generate one visual prompt via Groq, search Google Images, and download the first result."""
    
    # === 1️⃣ Generate image prompt ===
    chat = ChatGroq(api_key=os.getenv("GROQ_API_KEY"), model="openai/gpt-oss-20b")
    concept_text = "Neural network architecture with backpropagation for image recognition"
    prompt = f"Create a vivid cartoon-style image search query about: {concept_text}. Keep under 10 words."
    
    llm_response = chat.invoke(prompt)
    search_query = llm_response.content if hasattr(llm_response, "content") else str(llm_response)
    print(f"🔍 Search Query Generated by Groq: {search_query}")

    # === 2️⃣ Google Custom Search API ===
    api_key = os.environ["GOOGLE_API_KEY"]
    cx = os.environ["GOOGLE_CX"]
    search_url = "https://www.googleapis.com/customsearch/v1"
    params = {
        "q": search_query,
        "cx": cx,
        "key": api_key,
        "searchType": "image",
        "num": 1,
        "safe": "active"
    }

    resp = requests.get(search_url, params=params)
    data = resp.json()

    if "items" not in data:
        print(f"❌ No results found. Response: {data}")
        return

    image_url = data["items"][0]["link"]
    print(f"🖼️ Found Image URL: {image_url}")

    # === 3️⃣ Download the image ===
    img_dir = "images/test_one_image"
    os.makedirs(img_dir, exist_ok=True)
    img_path = os.path.join(img_dir, "sample_image.jpg")

    try:
        img_data = requests.get(image_url, timeout=10)
        img_data.raise_for_status()
        img = Image.open(io.BytesIO(img_data.content))
        img.save(img_path)
        print(f"✅ Image downloaded successfully: {img_path}")
    except Exception as e:
        print(f"⚠️ Image download failed: {e}")

# Run the test
test_single_image_generation()
